version: "3"

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - ":8001"

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - ":8002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - ":8003"

  databases:
    container_name: databases
    restart: always
    build: ./databases
    ports:
      - ":8004"
